name: Run Airflow DAG

on:
  workflow_dispatch:

jobs:
  run-airflow-dag:
    runs-on: ubuntu-latest

    env:
      AIRFLOW_HOME: /home/runner/airflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Airflow
        run: |
          python -m pip install --upgrade pip

          pip install "apache-airflow==2.10.5" \
            --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.11.txt"

      - name: Create Airflow Home
        run: |
          mkdir -p $AIRFLOW_HOME

      - name: Create airflow.cfg
        run: |
          airflow config list > /dev/null

          sed -i 's/load_examples = True/load_examples = False/g' \
          $AIRFLOW_HOME/airflow.cfg

      - name: Initialize Airflow DB
        run: |
          airflow db migrate

      - name: Copy DAGs
        run: |
          mkdir -p $AIRFLOW_HOME/dags
          cp dags/*.py $AIRFLOW_HOME/dags/

      - name: Show DAGs
        run: |
          airflow dags list

      - name: Test DAG
        run: |
          airflow tasks test \
          hello_airflow_github_actions \
          hello_task \
          2025-01-01
